name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f85fababab611311cc15a35a986ae1389734958916064f8ef99e578587d1e77e"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
