name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "457992eefde2f6fe56e29bc2b71154855f0165588d4d311507f59b5f3382030e"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
