name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1eec92bf1e8c04f4ae69b53843b3ccf2865c9415bdd3df0b5ce9bfb4a612409"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
