name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f05057e29a736e61e558c3d1c7611b188feb7e7285572d442793ccf4db0395c8"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
