name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c44c75bf459e659045c29c8413edc8932f3a1bb1d0c68ee21f48ab736df88787"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
