name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c46ed5f6945d422bf346fda27aef5860d6b15310b44098eb5b3e76eda173f28"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
