name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aabe3d8f8a8db900cb9ed3b51aa62a010f656c6570ce442ad4fdbf706ccf8a2"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
