name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "672723b443ba14a2337eccc75ec5b082a5eb73d10da949d5dc02485eedb49e68"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
