name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "337395d284f02840549c56ef7b58a648990e91ccc1585338fca1bb59b942eb6e"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
