name = "Minecraft Homecoming"
author = "minhtyfresh"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af2c284f31d9b30f77ccc713f58115b82c7c5a3d9d5410429a3e67079acbb17b"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
